CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(55) NOT NULL,
    creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE formats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(55) NOT NULL
);

CREATE TABLE decks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(55) NOT NULL,
    version INTEGER DEFAULT 1,
    format_id BIGINT REFERENCES formats(id),
    user_id BIGINT REFERENCES users(id),
    creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE metas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(55) NOT NULL,
    user_id BIGINT REFERENCES users(id),
    creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE opponent_decks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(55) NOT NULL,
    meta_id BIGINT REFERENCES metas(id),
    creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE matches (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    opponent_deck_id BIGINT REFERENCES opponent_decks(id),
    deck_id BIGINT REFERENCES decks(id),
    match_date DATE NOT NULL,
    creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);